### ISSUE TITLE
Better user experience when authenticating a user

### ISSUE THREAD

**Issue by Lamouresparus** [opendatakit/tool-suite-X#324] opened 2021-11-03 08:34 UTC
In the ODK-X survey app

<img src="https://user-images.githubusercontent.com/34775925/140028924-0827c18b-d2f6-4103-bf52-20a938492c74.jpeg" width="320" height="680">

When a new user has been authenticated and verification is successful.

<img src="https://user-images.githubusercontent.com/34775925/140028825-9b1df42e-7d6b-45f6-9a18-9b3eb8c54b2d.jpeg" width="320" height="680">

<img src="https://user-images.githubusercontent.com/34775925/140029133-4a66cce1-7593-4673-b04c-14b5b26c5fef.jpeg" width="320" height="680">

Clicking on the ok button in the alert dialog should take the user back to the previous screen and not remain on the authenticate new user screen.

<img src="https://user-images.githubusercontent.com/34775925/140029169-6a417bce-f10d-4c29-bc00-83026d93e6f7.jpeg" width="320" height="680">

Upon successful verification, clicking the ok button should pop back to the screen the user came in from. This is a better user experience, as the user is brought back to where they left off.

**Comment by wbrunette** [comment] 2021-11-03 17:40
Thank you for raising this issue. The good news is people are already working on re-implementing the sign-in workflow.

This is a duplicate of https://github.com/odk-x/tool-suite-X/issues/125 A new user interface is in the pipeline for release. It did not make it this release but will next release.

**Closed as completed by wbrunette** 2021-11-03 17:40 UTC
