### ISSUE TITLE
Update Deprecated assertThat in AlertNProgessMsgFragmentMgerTest

### ISSUE THREAD

**Issue by Lamouresparus** [opendatakit/tool-suite-X#445] opened 2023-10-25 08:24 UTC
**Description:**
The `assertThat` method used in the `AlertNProgessMsgFragmentMgerTest` is deprecated and should be updated to `MatcherAssert.assertThat` from `org.hamcrest.MatcherAssert.assertThat()` to maintain code quality and compatibility. This change ensures that our tests continue to function correctly with up-to-date libraries.

**Affected File:**
`AlertNProgessMsgFragmentMgerTest.java` in ODK-X Android Library

**Code to Update:**
In the `AlertNProgessMsgFragmentMgerTest` class, locate the deprecated `assertThat` method and update it to use `MatcherAssert.assertThat` from `org.hamcrest.MatcherAssert.assertThat()`.

```java
// Replace this deprecated assertThat with MatcherAssert.assertThat
// Deprecated:
assertThat(fragmentManager.findFragmentByTag(ALERT_DIALOG_TAG).isAdded(), is(true));
// Updated:
MatcherAssert.assertThat(fragmentManager.findFragmentByTag(ALERT_DIALOG_TAG).isAdded(), is(true));
```

**Expected Behavior:**

- Updating the deprecated `assertThat` should resolve any warnings and ensure the test code remains valid and compatible with the latest libraries.
- After making the change, rebuild and run the `AlertNProgessMsgFragmentMgerTest` test. The tests should pass.

**Additional Information:**
- Confirm that the updated code does not introduce any breaking changes to the existing test functionality.
- Ensure that all other tests and code in the file remain unaffected.

**Comment by Kemyikpe** [comment] 2023-10-25 08:24
@Lamouresparus  please can you assign to me? 🙏🙏🙏

**Comment by wbrunette** [comment] 2023-10-25 12:27
We will allow any Outreachy intern to make a PR demonstrating their solution so that people can have more contributions, as the contribution period is coming to an end. @Kemyikpe

**Comment by Chinex-Boroja** [comment] 2023-10-25 13:16
Hi @Lamouresparus @wbrunette, I just raised a [pull request ](https://github.com/odk-x/androidlibrary/pull/260)on this issue, kindly review. Thank you

**Comment by veekamunya** [comment] 2024-03-12 22:44
Hello, can i be assigned this issue of is it closed?

**Comment by wbrunette** [comment] 2024-03-12 23:47
@veekamunya if it still exists sure, but check the update-jdk11 to see if the problem is still there. A PR was merged with some amount of fixes.

**Comment by wbrunette** [comment] 2024-03-18 15:32
Confirmed complete

**Closed as completed by wbrunette** 2024-03-18 15:32 UTC
Labels: androidlibrary, easy win, good second issue
