### ISSUE TITLE
OUTREACHY SPRING 2023 STARTER ISSUE - Do this first

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#405] opened 2023-03-05 21:44 UTC
This issue is a getting starting issue for Outreachy intern applicants for Spring 2023. All intern applicants are expected to begin with this issue.

To start, please read the welcome post on the ODK-X Forum and join the ODK-X slack.
https://forum.odk-x.org/t/welcome-outreachy-applicants-spring-2023/2121?u=w_brunette

Next, we want you to experiment and familiarize yourself with the build tools. Please familiarize yourself with GitHub and CircleCI, as knowledge of these tools will be critical to a successful intern project application.
More information about CircleCI can be found reading: https://circleci.com/ and  https://circleci.com/integrations/github/
Both GitHub and CIrcleCI are free for public repositories on GitHub.

MAIN TASK: Set up a CircleCI automatic build for the ODK-X Suitcase repository in your GitHub account (do not run tests yet).
To complete this issue, you will need to first clone the “odk-x/suitcase” repository to your GitHub account. Next, you will need to set up CircleCI continuous build check for pull requests sent to your version of the Suitcase repository. NOTE: for this issue, you do NOT need to run any tests (Suitcase build defaults to not running tests, so do not try to turn it on). We are simply looking for CircleCI to build Suitcase.

VERIFICATION: Once you have CircleCI building a pull request for Suitcase, post a link to your suitcase repository. One of the mentors will test it by trying to submit a pull request to verify CircleCI is building Suitcase.

**Comment by nuilewis** [comment] 2023-03-06 16:27
Hello @wbrunette , I'm Nuikweh Lewis, and I just got approved for Outreachy. I would like to work on this issue, please. Thank you.

**Comment by Roseline-Bassey** [comment] 2023-03-06 16:37
Hey @wbrunette ,  My name is Roseline Bassey from Nigeria. I wanted to reach out and express my interest in contributing to ODK-X through the Outreachy 2023 internship. Specifically, I'm really excited about working on this particular issue.

**Comment by Goodiec** [comment] 2023-03-06 17:46
Hello @wbrunette, I'm Goodness, I am an Outreachy applicant and I am interested in the Create a GitHub and CircleCI based continuous build system for ODK-X project. Thank you for the instructions!

**Comment by S1Y333** [comment] 2023-03-06 17:49
Hi Waylon @wbrunette, nice to meet you. Can I also apply to this project? I am familiar with java programming and would like to know more about the pipeline. Thank you and I appreciate your consideration. Sylvia

**Comment by wbrunette** [comment] 2023-03-06 18:11
Anyone can apply for this project

**Comment by tr-sangale** [comment] 2023-03-06 18:34
hey @wbrunette , 
my outreachy initial application has been approved
I would like to work on this issue please.

**Comment by Goodiec** [comment] 2023-03-06 19:02
@wbrunette, kindly verify - https://github.com/Goodiec/Suitcase

**Comment by Ndacyayisenga-droid** [comment] 2023-03-06 19:13
@wbrunette can you assign this issue to me please

**Comment by Ndacyayisenga-droid** [comment] 2023-03-06 20:17
@wbrunette,
Verify here https://github.com/Ndacyayisenga-droid/suitcase

Note: Link to the PR of the config.yml template that initialised circle ci is merged https://github.com/Ndacyayisenga-droid/suitcase/pull/1

Here is the link to circle ci https://app.circleci.com/pipelines/github/Ndacyayisenga-droid/suitcase/2/workflows/c6f1e142-6e44-4c48-8e41-447c8461fcb9/jobs/2
<img width="1652" alt="Screenshot 1401-12-15 at 23 08 44" src="https://user-images.githubusercontent.com/58124613/223219856-f4102738-b434-47ef-ac62-d407a2d32fae.png">

**Comment by S1Y333** [comment] 2023-03-06 21:03
Hi @wbrunette, please verify here https://github.com/S1Y333/Suitcase, thank you!

**Comment by Roseline-Bassey** [comment] 2023-03-06 22:42
> Hey @wbrunette , My name is Roseline Bassey from Nigeria. I wanted to reach out and express my interest in contributing to ODK-X through the Outreachy 2023 internship. Specifically, I'm really excited about working on this particular issue.

Hello @wbrunette , please kindly verify here: https://github.com/Roseline-Bassey/suitcase

**Comment by CartoonistDev** [comment] 2023-03-06 23:11
Hi @wbrunette , My name is Chizzy Ibemeru from Nigeria. I am one of the outreachy interns, I would like to express my interest in contributing to ODK-X. I'm excited about working on this issue.

**Comment by CartoonistDev** [comment] 2023-03-07 06:19
@wbrunette trust you’re good, can you assign this issue to me? I’m yet to be assigned. Thanks

**Comment by Goodiec** [comment] 2023-03-07 06:31
> @wbrunette trust you’re good, can you assign this issue to me? I’m yet to be assigned. Thanks

Hi @CartoonistDev, I think you don't have to wait until you're assigned to this issue to work on it. You can go on to work on it and he'll add you to the issue when he can.

**Comment by CartoonistDev** [comment] 2023-03-07 07:10
> > @wbrunette trust you’re good, can you assign this issue to me? I’m yet to be assigned. Thanks
> 
> Hi @CartoonistDev, I think you don't have to wait until you're assigned to this issue to work on it. You can go on to work on it and he'll add you to the issue when he can.

Oh, thank you for your help

**Comment by nuilewis** [comment] 2023-03-07 08:54
Hello, @wbrunette. Please review this. [https://github.com/nuilewis/suitcase](https://github.com/nuilewis/suitcase) 

I was facing an issue with getting the build to work on my local machine. I am on Windows, and I realised it was because of the Maven version I was using. I used the latest available Maven which is version 3.9.0. Apparently, some kind of null exception occurs causing the build to fail. I finally had to use Maven 3.8.6 before I got it working.

Did anyone else face this issue?

I actually added a GitHub action to trigger the CircleCI build action only on Pull requests before realising I could easily do it with a toggle in CircleCI😅

[https://github.com/odk-x/suitcase/pull/79](https://github.com/odk-x/suitcase/pull/79)
I have submitted a PR for an update to the README, recommending the use of Maven 3.8.6. Please review when you can.

**Comment by Roseline-Bassey** [comment] 2023-03-07 09:12
> Hello, @wbrunette. Please review this. https://github.com/nuilewis/suitcase
> 
> I was facing an issue with getting the build to work on my local machine. I am on Windows, and I realised it was because of the Maven version I was using. I used the latest available Maven which is version 3.9.0. Apparently, some kind of null exception occurs causing the build to fail. I finally had to use Maven 3.8.6 before I got it working.
> 
> Did anyone else face this issue?

Hello @nuilewis , I'm glad to hear that you were able to solve the issue. I didn't encounter any problems, which may be due to the fact that I already had Maven 3.8.6 installed.

**Comment by nuilewis** [comment] 2023-03-07 09:47
> > Hello, @wbrunette. Please review this. https://github.com/nuilewis/suitcase
> > I was facing an issue with getting the build to work on my local machine. I am on Windows, and I realised it was because of the Maven version I was using. I used the latest available Maven which is version 3.9.0. Apparently, some kind of null exception occurs causing the build to fail. I finally had to use Maven 3.8.6 before I got it working.
> > Did anyone else face this issue?
> 
> Hello @nuilewis , I'm glad to hear that you were able to solve the issue. I didn't encounter any problems, which may be due to the fact that I already had Maven 3.8.6 installed.

Possibly. Once I used Maven 3.8.6, everything worked smoothly. thank you.

**Comment by cvemann** [comment] 2023-03-07 10:16
> @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase

Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/

It's important

**Comment by Roseline-Bassey** [comment] 2023-03-07 10:29
> > @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase
> 
> Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/
> 
> It's important

Thanks for informing us, @Cveman1

**Comment by Goodiec** [comment] 2023-03-07 10:32
> > @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase
> 
> Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/
> 
> It's important

Alright @Cveman1, will do that, thank you. Should we go on to look for issues to work on after the completion of this starter issue?

**Comment by nuilewis** [comment] 2023-03-07 11:07
> > > @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase
> > 
> > 
> > Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/
> > It's important
> 
> Alright @Cveman1, will do that, thank you. Should we go on to look for issues to work on after the completion of this starter issue?

Hey @Goodiec, I think for now we can just wait for feedback from the mentors. But if you can find something to work on, then by all means.

**Comment by Goodiec** [comment] 2023-03-07 11:18
> > > > @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase
> > > 
> > > 
> > > Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/
> > > It's important
> > 
> > 
> > Alright @Cveman1, will do that, thank you. Should we go on to look for issues to work on after the completion of this starter issue?
> 
> Hey @Goodiec, I think for now we can just wait for feedback from the mentors. But if you can find something to work on, then by all means.

Sure, thank you!

**Comment by cvemann** [comment] 2023-03-07 11:39
> > > @wbrunette, kindly verify - https://github.com/Goodiec/Suitcase
> > 
> > 
> > Apart from doing this, also try to submit your contributions here: https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/odk-x/create-a-github-and-circleci-based-continuous-buil/contributions/
> > It's important
> 
> Alright @Cveman1, will do that, thank you. Should we go on to look for issues to work on after the completion of this starter issue?

You can work on any other issue that you think relates to this particular project.

**Comment by S1Y333** [comment] 2023-03-07 23:14
Hi @Cveman1, does this issue count as one contribution to submit? Also, can you please help me check if my link is correct? Many thanks! 

> Hi @wbrunette, please verify here https://github.com/S1Y333/Suitcase, thank you!

**Comment by nuilewis** [comment] 2023-03-08 00:42
> Hi @Cveman1, does this issue count as one contribution to submit? Also, can you please help me check if my link is correct? Many thanks! 
> 
> > Hi @wbrunette, please verify here https://github.com/S1Y333/Suitcase, thank you!
> 
> 

Hello @S1Y333 , yes this can count as one contribution. And you can add it to the Outreachy website, and just leave the field that asks for the date the contribution was merged or accepted blank. And I think your link is correct, I think @wbrunette just wanted a link to your repository.

**Comment by S1Y333** [comment] 2023-03-08 03:10
@nuilewis Thanks for your reply, I think I need to do some revisions as I used the automatically generated config.yml.

**Comment by nuilewis** [comment] 2023-03-08 08:58
> @nuilewis Thanks for your reply, I think I need to do some revisions as I used the automatically generated config.yml.

Alright. The automatically generated config.yml just prints out a "hello world". You would have to edit it to set up a Maven environment, install Maven and Ant, and then add the commands to build the project.

**Comment by CartoonistDev** [comment] 2023-03-08 11:22
Hi @wbrunette please review my complete setup for this issue.

https://github.com/CartoonistDev/suitcase

**Comment by CartoonistDev** [comment] 2023-03-08 11:48
For those trying to do this issue this suggestions might help

- When you try to set up your pipeline on Circle CI after the initial set up you will need to install all the necessary dependencies on your CircleCI project(ant and maven) 
- This command should help you

                    steps:
                          - checkout
                          - run:
                              name: install dependencies
                              command: sudo apt-get update && sudo apt-get install -y ant maven
                    
                          - run:
                              name: Build Suitcase
                              command: |
                                cd dependencies
                                ant
                                cd ..
                                mvn clean package

- Please note not to have duplicates of "Steps" and remove the mvn test command since the issue instructs us not to run tests yet.

I was able to figure this out with help from @nuilewis and @Goodiec

**Comment by Goodiec** [comment] 2023-03-08 11:54
> For those trying to do this issue this suggestions might help
> 
> * When you try to set up your pipeline on Circle CI after the initial set up you will need to install all the necessary dependencies on your CircleCI project(ant and maven)
> * This command should help you
>   ```
>                 steps:
>                       - checkout
>                       - run:
>                           name: install dependencies
>                           command: sudo apt-get update && sudo apt-get install -y ant maven
>                 
>                       - run:
>                           name: Build Suitcase
>                           command: |
>                             cd dependencies
>                             ant
>                             cd ..
>                             mvn clean package
>   ```
> * Please note not to have duplicates of "Steps" and remove the mvn test command since the issue instructs us not to run tests yet.
> 
> I was able to figure this out with help from @nuilewis and @Goodiec

Glad to have been able to help and to see that you've been able to complete the task

**Comment by nuilewis** [comment] 2023-03-08 12:03
> For those trying to do this issue this suggestions might help
> 
> * When you try to set up your pipeline on Circle CI after the initial set up you will need to install all the necessary dependencies on your CircleCI project(ant and maven)
> * This command should help you
>   ```
>                 steps:
>                       - checkout
>                       - run:
>                           name: install dependencies
>                           command: sudo apt-get update && sudo apt-get install -y ant maven
>                 
>                       - run:
>                           name: Build Suitcase
>                           command: |
>                             cd dependencies
>                             ant
>                             cd ..
>                             mvn clean package
>   ```
> * Please note not to have duplicates of "Steps" and remove the mvn test command since the issue instructs us not to run tests yet.
> 
> I was able to figure this out with help from @nuilewis and @Goodiec

And one other thing, You should go to your CircleCI project dashboard

- Go to Project Settings > Advanced 
- And turn on "Only build pull requests" so CircleCI will only trigger a workflow on a pull request.

**Comment by NinaWendy** [comment] 2023-03-08 14:38
@wbrunette I am interested in contributing to this and would like to request to be assigned the issue to work on.  Can you please assign this issue to me.

**Comment by Goodiec** [comment] 2023-03-08 14:47
> @wbrunette I am interested in contributing to this and would like to request to be assigned the issue to work on. Can you please assign this issue to me.

Welcome @NinaWendy, you don't have to wait to be assigned, anyone can work on this.

**Comment by S1Y333** [comment] 2023-03-08 17:24
@nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you
<img width="936" alt="Screen Shot 2023-03-08 at 12 24 10 PM" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">

**Comment by nuilewis** [comment] 2023-03-08 17:31
> @nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you <img alt="Screen Shot 2023-03-08 at 12 24 10 PM" width="936" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">

Hi @S1Y333 
This is the same error I had when trying to build the project too. What version of Maven are you using?

**Comment by CartoonistDev** [comment] 2023-03-08 17:34
@S1Y333 did you go through the README file in the project and did all that was instructed? And like @nuilewis asked what version of Maven and Ant are you using.

**Comment by nuilewis** [comment] 2023-03-08 17:36
> > @nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you <img alt="Screen Shot 2023-03-08 at 12 24 10 PM" width="936" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">
> 
> Hi @S1Y333 This is the same error I had when trying to build the project too. What version of Maven are you using?

In my case, I found out it was because I was using Maven 3.9.0, the latest version on the website. But this seems to have a bug causing the build to fail. I finally had to use [Maven 3.8.6](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/) before I got mine working. Try that let's see if it works.

**Comment by S1Y333** [comment] 2023-03-08 18:38
> > > @nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you <img alt="Screen Shot 2023-03-08 at 12 24 10 PM" width="936" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">
> > 
> > 
> > Hi @S1Y333 This is the same error I had when trying to build the project too. What version of Maven are you using?
> 
> In my case, I found out it was because I was using Maven 3.9.0, the latest version on the website. But this seems to have a bug causing the build to fail. I finally had to use [Maven 3.8.6](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/) before I got mine working. Try that let's see if it works.
<img width="304" alt="Screen Shot 2023-03-08 at 1 37 38 PM" src="https://user-images.githubusercontent.com/105386341/223804883-11d2f981-a16b-4b2b-aecc-ae133a957a41.png">

My Maven is 3.8.6 from Eclipse.

**Comment by Goodiec** [comment] 2023-03-08 18:43
> > > > @nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you <img alt="Screen Shot 2023-03-08 at 12 24 10 PM" width="936" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">
> > > 
> > > 
> > > Hi @S1Y333 This is the same error I had when trying to build the project too. What version of Maven are you using?
> > 
> > 
> > In my case, I found out it was because I was using Maven 3.9.0, the latest version on the website. But this seems to have a bug causing the build to fail. I finally had to use [Maven 3.8.6](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/) before I got mine working. Try that let's see if it works.
> 
> <img alt="Screen Shot 2023-03-08 at 1 37 38 PM" width="304" src="https://user-images.githubusercontent.com/105386341/223804883-11d2f981-a16b-4b2b-aecc-ae133a957a41.png">
> 
> My Maven is 3.8.6 from Eclipse.

Can you confirm if you have Java installed

**Comment by S1Y333** [comment] 2023-03-08 18:46
> > > > > @nuilewis @Goodiec Hi, can you please help me take a look at this error when I am trying to run the maven project? Thank you <img alt="Screen Shot 2023-03-08 at 12 24 10 PM" width="936" src="https://user-images.githubusercontent.com/105386341/223785160-0f23096c-4b5c-4f90-8639-fcccedd26914.png">
> > > > 
> > > > 
> > > > Hi @S1Y333 This is the same error I had when trying to build the project too. What version of Maven are you using?
> > > 
> > > 
> > > In my case, I found out it was because I was using Maven 3.9.0, the latest version on the website. But this seems to have a bug causing the build to fail. I finally had to use [Maven 3.8.6](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/) before I got mine working. Try that let's see if it works.
> > 
> > 
> > <img alt="Screen Shot 2023-03-08 at 1 37 38 PM" width="304" src="https://user-images.githubusercontent.com/105386341/223804883-11d2f981-a16b-4b2b-aecc-ae133a957a41.png">
> > My Maven is 3.8.6 from Eclipse.
> 
> Can you confirm if you have Java installed

<img width="339" alt="Screen Shot 2023-03-08 at 1 45 54 PM" src="https://user-images.githubusercontent.com/105386341/223806490-2acda81b-35c5-4ec2-8137-834603731c5d.png">

Yes

**Comment by tr-sangale** [comment] 2023-03-08 20:10
@wbrunette can you please verify https://github.com/tr-sangale/suitcase 
and also, should i submit the form at outreachy , and count this as a contribution??

**Comment by Roseline-Bassey** [comment] 2023-03-08 21:00
> @wbrunette can you please verify https://github.com/tr-sangale/suitcase and also, should i submit the form at outreachy , and count this as a contribution??

@tr-sangale, yes you can record this on the outreach website as part of your contributions.

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-09 13:15
Your contributions can only be recorded once it's accepted

**Comment by Dee-Tyan** [comment] 2023-03-09 19:42
Hi @wbrunette, here is my implementation: https://github.com/Dee-Tyan/suitcase

**Comment by Dee-Tyan** [comment] 2023-03-09 20:46
Hi @wbrunette and @Cveman1, the instructions say "clone" the repo to get a copy, shouldn't that be "fork"?

**Comment by Ndacyayisenga-droid** [comment] 2023-03-09 21:15
> Hi @wbrunette and @Cveman1, the instructions say "clone" the repo to get a copy, shouldn't that be "fork"?

@Dee-Tyan, you may go through to much hustle just incase you use a forked repository since it is always connected to the updtream and it contains odk-x's initial github configurations.
I think the easiest and a better way is to clone the repository and then delete the .git file to loose odk-x's git initialisations and then do `git init` again to initate the repository with your own git configurations then push to github

**Comment by Dee-Tyan** [comment] 2023-03-09 21:18
> > Hi @wbrunette and @Cveman1, the instructions say "clone" the repo to get a copy, shouldn't that be "fork"?
> 
> @Dee-Tyan, you may go through to much hustle just incase you use a forked repository since it is always connected to the updtream and it contains odk-x's initial github configurations. I think the easiest and a better way is to clone the repository and then delete the .git file to loose odk-x's git initialisations and then do `git init` again to initate the repository with your own git configurations then push to github

Oh, this helps a lot. Thank you!

**Comment by wbrunette** [comment] 2023-03-09 21:37
@Ndacyayisenga-droid and @Dee-Tyan you actually do NOT want to do that. The .git folder keeps the commit history. To merge back to the ODK-X repo git needs the commit history in tact to figure out what changes you made.

**Comment by chysomee** [comment] 2023-03-09 21:54
Hello @wbrunette , Thanks for pointing out when I made a wrong pull request earlier. I have corrected it. Kindly review via this [link](https://github.com/chysomee/suitcase)

**Comment by Dee-Tyan** [comment] 2023-03-09 21:58
> @Ndacyayisenga-droid and @Dee-Tyan you actually do NOT want to do that. The .git folder keeps the commit history. To merge back to the ODK-X repo git needs the commit history in tact to figure out what changes you made.

Oh wow. So should I clone as is, or just fork it?

**Comment by wbrunette** [comment] 2023-03-09 21:59
You should fork, then clone to your computer using your repository.

**Comment by Dee-Tyan** [comment] 2023-03-09 22:00
> You should fork, then clone to your computer using your repository.

Alright, thank you!
 
Here is my copy for verification: https://github.com/Dee-Tyan/suitcase

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-10 10:03
@

> Hello @wbrunette , Thanks for pointing out when I made a wrong pull request earlier. I have corrected it. Kindly review via this [link](https://github.com/chysomee/suitcase)

 Your circleci build failed, make sure the maven and ant commands are correctly written.

**Comment by NinaWendy** [comment] 2023-03-10 10:17
@Redeem-Grimm-Satoshi Kindly check mine at https://github.com/NinaWendy/suitcase/tree/circleci-project-setup

**Comment by darellwest** [comment] 2023-03-13 06:58
I am an outreachy intern and I joined this team not too long. I have checked circlecI and github. I am ready to work on this

**Comment by Goodiec** [comment] 2023-03-13 07:03
> I am an outreachy intern and I joined this team not too long. I have checked circlecI and github. I am ready to work on this

Welcome @darellwest, you can go ahead and work on this issue. Feel free to ask questions if you need clarification on anything.

**Comment by darellwest** [comment] 2023-03-13 10:31
Hello @wbrunette  please help me check my repository here https://github.com/darellwest/odk-x-suitcase to see if circleCI is building suitcase. Thanks

**Comment by darellwest** [comment] 2023-03-13 11:38
@Goodiec my build fails, when I check to see what the problem is I see this "
/bin/sh: sudo: not found" I have checking for solutions, I don't know if you can help me on this

**Comment by Goodiec** [comment] 2023-03-13 12:00
> @Goodiec my build fails, when I check to see what the problem is I see this " /bin/sh: sudo: not found" I have checking for solutions, I don't know if you can help me on this

@darellwest, where do you get this? Can you share a screenshot?

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-13 15:17
@darellwest You're not building it correctly. What you did is just an initial circleci setup and probably with a wrong image and no build commands!

Just put in a little bit more effort, You'll get it right :)

**Comment by darellwest** [comment] 2023-03-13 16:17
Thank very much @Redeem-Grimm-Satoshi I have been battling this since morning, just got it right few minutes ago.

**Comment by darellwest** [comment] 2023-03-13 16:19
Hello @Redeem-Grimm-Satoshi please help me check my repository here https://github.com/darellwest/odk-x-suitcase to see if circleCI is building suitcase. Thanks

**Comment by wbrunette** [comment] 2023-03-13 16:21
All, @Redeem-Grimm-Satoshi is doing the checking for this issue

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-14 08:50
@darellwest you used  `image: alpine:3.15` as your image. Can you explain?

**Comment by darellwest** [comment] 2023-03-14 15:19
@Redeem-Grimm-Satoshi I changed it already, please check again. I was learning everything about circleci and docker and did not understand much about the image thing originally, plus I already corrected it but didn't merge it into the master branch, which I did few hours ago. Please check it here again https://github.com/darellwest/odk-x-suitcase
![Screenshot_2023-03-14-17-07-26-298_com android chrome](https://user-images.githubusercontent.com/43733122/225067910-bba82f9f-8bd2-42c3-86e6-e6b0e8e31e8f.jpg)

**Comment by Dorcas-BD** [comment] 2023-03-16 20:44
Hello @wbrunette and @Cveman1, please help me check my repository https://github.com/Dorcas-BD/suitcase

**Comment by darellwest** [comment] 2023-03-17 10:31
> Hello @wbrunette and @Cveman1, please help me check my repository https://github.com/Dorcas-BD/suitcase

I think @Redeem-Grimm-Satoshi is the mentor responsible for doing the review @Dorcas-BD

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-17 14:10
> Hello @wbrunette and @Cveman1, please help me check my repository https://github.com/Dorcas-BD/suitcase

@Dorcas-BD reviewed your repo :)

**Comment by Dorcas-BD** [comment] 2023-03-17 15:22
Ohh, Thanks, @darellwest.



> > Hello @wbrunette and @Cveman1, please help me check my repository https://github.com/Dorcas-BD/suitcase
> 
> I think @Redeem-Grimm-Satoshi is the mentor responsible for doing the review @Dorcas-BD

Ohh, Thanks, @darellwest

**Comment by Dorcas-BD** [comment] 2023-03-17 15:22
> > Hello @wbrunette and @Cveman1, please help me check my repository https://github.com/Dorcas-BD/suitcase
> 
> @Dorcas-BD reviewed your repo :)

Thank you @Redeem-Grimm-Satoshi

**Comment by Redeem-Grimm-Satoshi** [comment] 2023-03-18 17:47
@Dorcas-BD You did a great job! You're good to go :)

**Comment by Dorcas-BD** [comment] 2023-03-18 20:32
> @Dorcas-BD You did a great job! You're good to go :)

Thank you! @Redeem-Grimm-Satoshi

**Comment by StrangeJay** [comment] 2023-03-27 13:57
Hello @wbrunette , I'm Jamillah Bello, and I just got approved for Outreachy. I would like to work on this issue, please. Thank you.

**Comment by wbrunette** [comment] 2023-03-27 15:29
@StrangeJay welcome! Feel free to work on any issue that starts with OUTREACHY SPRING 2023 in the title.

**Comment by MariaAngella** [comment] 2023-10-03 01:25
Hello there,

I'm an Outreachy applicant for the winter 2023 season, can I please work on this issue.

Thank you and regards,
Maria Angella

**Comment by Tee-works** [comment] 2023-10-03 02:46
@wbrunette hello I’m Iyanu, an outreachy applicant and I can’t wait to solve and contribute to this issue. Please kindly assign this issue to me so I can get right on to solving it. Thank you.

**Comment by Goodiec** [comment] 2023-10-03 03:01
Hello @MariaAngella, @Tee-works, this issue was specifically for the last Outreachy round and I don't think it's still open for contributions. You can look for other issues related to the project(s) you're interested in.

**Comment by Tee-works** [comment] 2023-10-03 03:04
> Hello @MariaAngella, @Tee-works, this issue was specifically for the last Outreachy round and I don't think it's still open for contributions. You can look for other issues related to the project(s) you're interested in. 

Okay thank you will check out for new issues

**Comment by Chinex-Boroja** [comment] 2023-10-03 09:14
Hi @Goodiec , there are no new issues for the current Outreachy round, so I don't know when new issues will be released, do you have any ideas?

**Comment by Goodiec** [comment] 2023-10-03 10:25
> Hi @Goodiec , there are no new issues for the current Outreachy round, so I don't know when new issues will be released, do you have any ideas?

@Chinex-Boroja, look out issues that have the tags “good first issue” and “easy win”, you can work on any of those.

**Comment by Chinex-Boroja** [comment] 2023-10-03 10:37
@Goodiec the recent tags for "good first issue" are for the last Outreachy Spring period. I have checked, and there are no updated "good first issue or easy win" for the Winter period. Or probably I am missing something

**Closed as completed** 2023-10-03 11:04 UTC
Labels: good first issue, Outreachy Spring 2023
